"""
Rank 39-CYC: GF(7) Group Code Check for f_MDL Orbit
EPIC_072 — GTE Ontological Unification

Investigates whether the f_MDL orbit {gen₁, gen₂, gen₃, vacuum}
has the structure of a group code over GF(7).
"""

from pathlib import Path
SCRIPT_DIR = Path(__file__).resolve().parent

gen1 = [1, 5, 2, 2, 1]
gen2 = [2, 5, 2, 0, 2]
gen3 = [5, 6, 5, 3, 5]
vacuum = [0, 0, 0, 0, 0]
orbit = [gen1, gen2, gen3, vacuum]
orbit_names = {tuple(gen1): 'gen1', tuple(gen2): 'gen2',
               tuple(gen3): 'gen3', tuple(vacuum): 'vacuum'}

def name_of(v):
    t = tuple(v)
    return orbit_names.get(t, str(v))

def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    g, x, y = extended_gcd(b % a, a)
    return g, y - (b // a) * x, x

def mod_inv(a, m):
    g, x, _ = extended_gcd(a % m, m)
    if g != 1:
        return None
    return x % m

print("=" * 65)
print("Rank 39-CYC: GF(7) Code Structure of f_MDL Orbit")
print("=" * 65)
print(f"\nOrbit elements:")
print(f"  gen1   = {gen1}")
print(f"  gen2   = {gen2}")
print(f"  gen3   = {gen3}")
print(f"  vacuum = {vacuum}")

# ─────────────────────────────────────────────────────────────────────
# Q1: Closed under pointwise addition mod 7?
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q1: Additive closure (pointwise + mod 7)")
print("─" * 65)
additive_closed = True
for a, an in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
    for b, bn in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
        s = [(a[i]+b[i]) % 7 for i in range(5)]
        in_orbit = s in orbit
        if not in_orbit:
            additive_closed = False
        mark = '✓ IN orbit' if in_orbit else '✗ NOT in orbit'
        print(f"  {an} + {bn} = {s}   {mark}")
print(f"\n  → Additive closure: {'YES' if additive_closed else 'NO'}")

# ─────────────────────────────────────────────────────────────────────
# Q2: Closed under pointwise multiplication mod 7?
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q2: Multiplicative closure (pointwise * mod 7)")
print("─" * 65)
mult_closed = True
for a, an in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
    for b, bn in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
        p = [(a[i]*b[i]) % 7 for i in range(5)]
        in_orbit = p in orbit
        if not in_orbit:
            mult_closed = False
        mark = '✓ IN orbit' if in_orbit else '✗ NOT in orbit'
        print(f"  {an} * {bn} = {p}   {mark}")
print(f"\n  → Multiplicative closure: {'YES' if mult_closed else 'NO'}")

# ─────────────────────────────────────────────────────────────────────
# Q3: Scalar multiplication α * v (mod 7)
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q3: Scalar multiplication — α · orbit_element (mod 7)")
print("─" * 65)
hits = []
for alpha in range(1, 7):
    for v, vn in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
        p = [(alpha*x) % 7 for x in v]
        in_orbit = p in orbit
        if in_orbit:
            hits.append((alpha, vn, p, name_of(p)))
            print(f"  α={alpha}: {alpha}·{vn} = {p}  → {name_of(p)} ✓")

if not hits:
    print("  (no scalar multiple of any orbit element lands in the orbit)")
else:
    print(f"\n  → {len(hits)} scalar hits found")

# ─────────────────────────────────────────────────────────────────────
# Q4: Cubic roots of unity in GF(7)
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q4: Color subgroup {1,2,4} as cubic roots of unity in GF(7)")
print("─" * 65)
cubic_roots = []
for x in range(1, 7):
    if pow(x, 3, 7) == 1:
        cubic_roots.append(x)
print(f"  Solutions to x³ ≡ 1 (mod 7): {cubic_roots}")
for x in cubic_roots:
    print(f"    {x}³ mod 7 = {pow(x, 3, 7)}")
print(f"\n  Color subgroup {{1,2,4}}:")
for x in [1, 2, 4]:
    print(f"    {x}³ mod 7 = {pow(x, 3, 7)}  {'✓ cubic root of unity' if pow(x,3,7)==1 else '✗'}")
if set(cubic_roots) == {1, 2, 4}:
    print("\n  → {{1,2,4}} ARE the cubic roots of unity in GF(7) ✓")
else:
    print(f"\n  → Cubic roots of unity in GF(7): {cubic_roots}")

# Order structure of GF(7)*
print("\n  Order structure of GF(7)* = Z₆:")
g = 3  # 3 is a primitive root mod 7
for k in range(6):
    print(f"    3^{k} mod 7 = {pow(3,k,7)}")

# Subgroup generated by each element
print("\n  Subgroup ⟨x⟩ in GF(7)* for each x:")
for x in range(1, 7):
    sub = set()
    cur = 1
    for _ in range(7):
        sub.add(cur)
        cur = (cur * x) % 7
        if cur == 1:
            sub.add(1)
            break
    # multiplicative order
    order = 1
    cur = x
    while cur != 1:
        cur = (cur * x) % 7
        order += 1
    print(f"    ⟨{x}⟩ = {sorted(sub)}, order {order}")

# ─────────────────────────────────────────────────────────────────────
# Q5: Multiplicative ratios between orbit elements
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q5: Componentwise multiplicative ratios between orbit elements")
print("─" * 65)
pairs = [('gen2', gen2, 'gen1', gen1),
         ('gen3', gen3, 'gen2', gen2),
         ('gen3', gen3, 'gen1', gen1)]
for num_n, num_v, den_n, den_v in pairs:
    print(f"\n  {num_n}[i] / {den_n}[i] (mod 7):")
    ratios = []
    for i in range(5):
        if den_v[i] != 0 and num_v[i] != 0:
            ratio = (num_v[i] * mod_inv(den_v[i], 7)) % 7
            ratios.append(ratio)
            print(f"    comp {i}: {num_v[i]}/{den_v[i]} = {ratio} (mod 7)")
        elif den_v[i] == 0 and num_v[i] == 0:
            print(f"    comp {i}: 0/0 (both zero — indeterminate)")
            ratios.append(None)
        elif den_v[i] == 0:
            print(f"    comp {i}: {num_v[i]}/0 (undefined — {den_n}=0 but {num_n}≠0)")
            ratios.append(None)
    non_none = [r for r in ratios if r is not None]
    if len(set(non_none)) == 1:
        print(f"    → ALL defined ratios equal {non_none[0]}: {num_n} = {non_none[0]}·{den_n} (mod 7) ✓")
    else:
        print(f"    → Ratios NOT constant: {ratios} (no uniform scalar)")

# ─────────────────────────────────────────────────────────────────────
# Q6: Linear map M: gen1 → gen2 → gen3 over GF(7)?
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q6: Is there a 5×5 matrix M over GF(7) with M·gen1=gen2, M·gen2=gen3?")
print("─" * 65)

# Represent gen1, gen2, gen3 as column vectors
# We look for a diagonal matrix (simplest) first: M = diag(m0,...,m4)
# diag: m_i * gen1[i] = gen2[i] for i = 0..4
print("\n  (a) Diagonal matrix check:")
diag_works_12 = True
diag_12 = []
for i in range(5):
    if gen1[i] == 0:
        if gen2[i] == 0:
            diag_12.append('any')
        else:
            diag_12.append(None)
            diag_works_12 = False
    else:
        m = (gen2[i] * mod_inv(gen1[i], 7)) % 7
        diag_12.append(m)
print(f"    M such that M·gen1 = gen2: diag = {diag_12}")
print(f"    → {'Diagonal solution EXISTS' if diag_works_12 else 'NO diagonal solution (gen1[i]=0 but gen2[i]≠0)'}")

# Check same M on gen2 → gen3
if diag_works_12:
    gen3_pred = [(diag_12[i] if diag_12[i] != 'any' else 0) * gen2[i] % 7 for i in range(5)]
    match = gen3_pred == gen3
    print(f"\n    Same M applied to gen2: {gen3_pred}")
    print(f"    Expected gen3:           {gen3}")
    print(f"    → Match: {'YES ✓' if match else 'NO ✗'}")

# Non-diagonal: find any linear map via Vandermonde structure
print("\n  (b) Scalar multiplication structure:")
# Check if orbit elements lie on a rational normal curve in GF(7)^5
# i.e., if gen1 = (α^0, α^1, α^2, α^3, α^4) for some α ∈ GF(7)*
print("  Checking if orbit elements are power sequences α^k (k=0..4):")
for v, vn in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
    for alpha in range(1, 7):
        powers = [pow(alpha, k, 7) for k in range(5)]
        if powers == v:
            print(f"    {vn} = [{alpha}^0, {alpha}^1, ..., {alpha}^4] mod 7 = {powers} ✓")
            break
    else:
        # Check with offset: v[i] = c * alpha^i
        found = False
        for alpha in range(1, 7):
            for c in range(1, 7):
                powers = [(c * pow(alpha, k, 7)) % 7 for k in range(5)]
                if powers == v:
                    print(f"    {vn} = {c}·[{alpha}^0, {alpha}^1, ..., {alpha}^4] mod 7 = {powers} ✓")
                    found = True
                    break
            if found:
                break
        if not found:
            print(f"    {vn}: not of the form c·α^k for any c,α ∈ GF(7)*")

# ─────────────────────────────────────────────────────────────────────
# Q7: Reed-Solomon structure — evaluate polynomial at 5 points?
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q7: RS codeword check — is each orbit element a polynomial over GF(7)?")
print("─" * 65)
# An RS(5,k) codeword over GF(7) with evaluation points {x0,...,x4} ⊆ GF(7)
# is a vector (p(x0), p(x1), ..., p(x4)) for polynomial p of degree < k.
# Try evaluation points = {1,2,3,4,5} or {0,1,2,3,4} etc.

def poly_eval(coeffs, x, m):
    """Evaluate polynomial sum(coeffs[i]*x^i) mod m."""
    return sum(c * pow(x, i, m) % m for i, c in enumerate(coeffs)) % m

eval_points_candidates = [
    [1, 2, 3, 4, 5],
    [0, 1, 2, 3, 4],
    [1, 2, 4, 3, 6],
    [3, 4, 5, 6, 1],
]

for pts in eval_points_candidates:
    print(f"\n  Evaluation points: {pts}")
    for v, vn in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
        # Lagrange interpolation: find unique poly of degree ≤ 4 through (pts[i], v[i])
        # Check if it has low degree (say ≤ 2 for k=3 RS code)
        # Compute via solving linear system
        # Use the Vandermonde system: sum_j a_j * pts[i]^j = v[i]
        # We'll just check degree-2 existence: 3 unknowns, try all degree-2 polys
        found_low = False
        # degree ≤ 1: v[i] = a + b*pts[i]
        # need to interpolate from 2 points and check remaining 3
        for a in range(7):
            for b in range(7):
                vals = [(a + b*x) % 7 for x in pts]
                if vals == v:
                    print(f"    {vn}: degree-1 poly f(x)={a}+{b}x over pts {pts} ✓")
                    found_low = True
                    break
            if found_low:
                break
        if not found_low:
            # degree ≤ 2
            for a in range(7):
                for b in range(7):
                    for c in range(7):
                        vals = [(a + b*x + c*x*x) % 7 for x in pts]
                        if vals == v:
                            print(f"    {vn}: degree-2 poly f(x)={a}+{b}x+{c}x² ✓")
                            found_low = True
                            break
                    if found_low:
                        break
                if found_low:
                    break
        if not found_low:
            print(f"    {vn}: no degree-≤2 polynomial over eval pts {pts}")

# ─────────────────────────────────────────────────────────────────────
# Q8: What is the full algebraic closure of the orbit under all GF(7) ops?
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q8: Algebraic closure — orbit under all scalar multiples")
print("─" * 65)
all_scalar_multiples = set()
for alpha in range(7):  # include 0 (gives vacuum)
    for v in [gen1, gen2, gen3]:
        p = tuple((alpha*x) % 7 for x in v)
        all_scalar_multiples.add(p)
all_scalar_multiples.add(tuple(vacuum))

print(f"  All scalar multiples α·orbit (α ∈ GF(7)) for nontrivial orbit elements:")
for s in sorted(all_scalar_multiples):
    print(f"    {list(s)}  ({'IN original orbit' if list(s) in orbit else 'extended'})")

print(f"\n  Total elements in scalar closure: {len(all_scalar_multiples)}")
print(f"  Original orbit size: 4")

# ─────────────────────────────────────────────────────────────────────
# Q9: Orbit under f_MDL as a coset of (Z₇*)^5
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q9: Is {gen1, gen2, gen3} a coset of a subgroup of (Z₇*)^5?")
print("─" * 65)
# The multiplicative group (Z₇*)^5 has order 6^5 = 7776
# A subgroup of index 3 (order 2592) would give exactly 3 cosets
# Check if gen2 = m * gen1 (componentwise) for some m ∈ (Z₇*)^5
print("\n  Checking if any (Z₇*)^5 element maps gen1 → gen2:")
found_coset_map = False
for m0 in range(1,7):
    for m1 in range(1,7):
        for m2 in range(1,7):
            for m3 in range(1,7):
                for m4 in range(1,7):
                    m = [m0,m1,m2,m3,m4]
                    prod = [(m[i]*gen1[i]) % 7 for i in range(5)]
                    if prod == gen2:
                        # Check if same m maps gen2 → gen3
                        prod2 = [(m[i]*gen2[i]) % 7 for i in range(5)]
                        if prod2 == gen3:
                            print(f"  Found m = {m}:")
                            print(f"    m·gen1 = {prod} = gen2 ✓")
                            print(f"    m·gen2 = {prod2} = gen3 ✓")
                            # Apply again: m·gen3 = ?
                            prod3 = [(m[i]*gen3[i]) % 7 for i in range(5)]
                            in_orbit = prod3 in orbit
                            print(f"    m·gen3 = {prod3} → {name_of(prod3)} {'✓' if in_orbit else '✗'}")
                            found_coset_map = True
                            break
                    if found_coset_map:
                        break
                if found_coset_map:
                    break
            if found_coset_map:
                break
        if found_coset_map:
            break
    if found_coset_map:
        break

if not found_coset_map:
    print("  No single m ∈ (Z₇*)^5 maps gen1→gen2 AND gen2→gen3.")
    # Check gen1 → gen2 alone
    print("\n  Maps m ∈ (Z₇*)^5 with m·gen1 = gen2 (ignoring gen3):")
    count = 0
    examples = []
    for m0 in range(1,7):
        for m1 in range(1,7):
            for m2 in range(1,7):
                for m3 in range(1,7):
                    for m4 in range(1,7):
                        m = [m0,m1,m2,m3,m4]
                        prod = [(m[i]*gen1[i]) % 7 for i in range(5)]
                        if prod == gen2:
                            count += 1
                            if len(examples) < 5:
                                examples.append(m)
    print(f"  Found {count} maps; first few: {examples}")

# ─────────────────────────────────────────────────────────────────────
# Q10: Summary of Z₇ winding number algebra
# ─────────────────────────────────────────────────────────────────────
print("\n" + "─" * 65)
print("Q10: Z₇ winding number interpretation of orbit elements")
print("─" * 65)
print("\n  Orbit element winding numbers (physical interpretation):")
print("  gen1 = [1,5,2,2,1]: net Z₇ winding = 1+5+2+2+1 =", sum(gen1) % 7, "(mod 7)")
print("  gen2 = [2,5,2,0,2]: net Z₇ winding = 2+5+2+0+2 =", sum(gen2) % 7, "(mod 7)")
print("  gen3 = [5,6,5,3,5]: net Z₇ winding = 5+6+5+3+5 =", sum(gen3) % 7, "(mod 7)")
print("  vacuum = [0,0,0,0,0]: net = 0")

print("\n  Color subgroup action on orbit:")
color_sub = [1, 2, 4]  # cubic roots of unity mod 7
for alpha in color_sub:
    for v, vn in [(gen1,'gen1'), (gen2,'gen2'), (gen3,'gen3')]:
        p = [(alpha*x) % 7 for x in v]
        print(f"  {alpha}·{vn} = {p}  → {name_of(p)}")

# ─────────────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("SUMMARY OF FINDINGS")
print("=" * 65)
print("""
1. ADDITIVE CLOSURE: NO — orbit is NOT a linear code over GF(7).

2. MULTIPLICATIVE CLOSURE (componentwise): check above results.

3. SCALAR MULTIPLICATION: 
   - α·gen_i ∈ orbit for specific (α, gen_i) pairs listed above.

4. CUBIC ROOTS OF UNITY: 
   - {1,2,4} ARE the cubic roots of unity in GF(7).
   - These form the unique order-3 subgroup of GF(7)* ≅ Z₆.

5. COMPONENTWISE RATIOS:
   - gen2/gen1, gen3/gen2, gen3/gen1 componentwise (mod 7) — see Q5 output.
   - If ratios are constant → uniform scalar relationship.
   - If non-constant → no single scalar links the orbit elements.

6. LINEAR MAP:
   - Diagonal matrix M with M·gen1 = gen2 — see Q6 output.
   - Whether same M sends gen2 → gen3 — see Q6 output.

7. RS CODEWORD STRUCTURE:
   - Low-degree polynomial evaluations — see Q7 output.

8. COSET STRUCTURE:
   - Single element of (Z₇*)^5 mapping gen1→gen2→gen3 — see Q9.
""")
