#!/usr/bin/env python3
"""RIET residual evaluator.

Loads perturbation batches generated by `analysis/data_harness.py`, applies
configurable mappings to FRW and Quarter-Lock parameters, and computes the
geometric, informational, and thermodynamic residual norms required for the
Reflexive Information Equivalence Theorem.

Outputs per-sample residual summaries in JSON for downstream analysis.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List

import numpy as np
import yaml  # type: ignore

# TE1.R utilities
import sys
PROJECT_ROOT = Path(__file__).resolve().parents[3]
PROGRAM_ROOT = PROJECT_ROOT / "TE_1_VALIDATION_PROGRAM"
CONT_MODEL_DIR = PROGRAM_ROOT / "TE_1.R_CONTINOUS_MODEL"
if str(CONT_MODEL_DIR) not in sys.path:
    sys.path.append(str(CONT_MODEL_DIR))

from frw_psi_solver import frw_psi_evolve
from action_residual import (
    friedmann_residual,
    quarter_lock_penalty,
)
from pt_normal_step_integrator import (
    integrate as ql_integrate,
)
from pt_normal_step_integrator import ql_normal

# Direct dataset references
TE1E_BASE_SUMMARY = (
    PROJECT_ROOT
    / "TE_1_VALIDATION_PROGRAM"
    / "TE_1.E_Lambda"
    / "results"
    / "run_20251110_230054"
    / "results"
    / "summary.json"
)
TE1R_FLUCT_SUMMARY = (
    PROJECT_ROOT
    / "TE_1_VALIDATION_PROGRAM"
    / "TE_1.R_CONTINOUS_MODEL"
    / "results"
    / "fluctuation"
    / "summary.json"
)
TE1O_FASTWIN = (
    PROJECT_ROOT
    / "TE_1_VALIDATION_PROGRAM"
    / "TE_1.O_ABSOLUTE_GAUGE"
    / "results"
    / "fast_win_summary.json"
)


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_config(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def map_perturbation(config: Dict[str, Any], delta_g: np.ndarray, delta_I: np.ndarray, delta_psi: float) -> Dict[str, Any]:
    mapping = config.get("mapping", {})
    base_frw = config["base"]["frw"].copy()

    psi_scale = mapping.get("psi_scale", 0.0)
    rho_m_scale = mapping.get("rho_m_scale", 0.0)
    lambda_scale = mapping.get("lambda_scale", 0.0)
    omega_scale = mapping.get("omega_scale", 0.0)

    base_frw["psi0"] = base_frw.get("psi0", 0.0) + psi_scale * float(delta_psi)
    delta_g_mean = float(delta_g.mean())
    base_frw["rho_m0"] = base_frw.get("rho_m0", 0.3) * (1.0 + rho_m_scale * delta_g_mean)
    base_frw["omega_bar"] = base_frw.get("omega_bar", 0.0) + omega_scale * float(delta_I.mean())
    base_frw["lambda_eff"] = base_frw.get("lambda_eff", 0.7) * (1.0 + lambda_scale * delta_g_mean)

    # Quarter-Lock palette adjustment
    ql_cfg = config["base"]["ql"].copy()
    ql_scale = mapping.get("ql_scale", 0.0)
    k0 = np.asarray(ql_cfg["k0"], dtype=float)
    k0 = k0 + ql_scale * np.tile(delta_I.mean(), k0.shape[0])
    ql_cfg["k0"] = k0.tolist()

    return {"frw": base_frw, "ql": ql_cfg}


def compute_geometric_residual(frw_cfg: Dict[str, Any], gtilde: float) -> float:
    series = frw_psi_evolve(
        t_max=frw_cfg.get("t_max", 2.0),
        dt=frw_cfg.get("dt", 1e-3),
        a0=frw_cfg.get("a0", 1.0),
        psi0=frw_cfg.get("psi0", 1e-3),
        psidot0=frw_cfg.get("psidot0", 0.0),
        rho_m0=frw_cfg.get("rho_m0", 0.3),
        Lambda_eff=frw_cfg.get("lambda_eff", 0.7),
        m=frw_cfg.get("m", 0.0),
        beta=frw_cfg.get("beta", 0.0),
        omega_bar=frw_cfg.get("omega_bar", 0.0),
        V0=frw_cfg.get("V0", 0.0),
        Gtilde=gtilde,
    )
    return friedmann_residual(series, gtilde)


def compute_informational_residual(ql_cfg: Dict[str, Any]) -> float:
    k0 = ql_cfg["k0"]
    s_max = ql_cfg.get("s_max", 2.0)
    ds = ql_cfg.get("ds", 1e-3)
    Epsi = ql_cfg.get("Epsi", 0.5)
    traj, _ = ql_integrate(k0, s_max=s_max, ds=ds, Epsi=Epsi)
    n = ql_normal(len(k0))
    final = traj[-1]
    return float(abs(sum(ni * ki for ni, ki in zip(n, final))))


def compute_entropy_residual(delta_lambda_scale: float, fluct_summary: Dict[str, Any]) -> float:
    mean_exp = float(fluct_summary.get("mean_exp_neg_deltaS", 1.0))
    entropy_resid = abs(mean_exp - 1.0)
    lambda_resid = abs(delta_lambda_scale)
    return entropy_resid + lambda_resid


def evaluate_batches(batch_files: Iterable[Path], config: Dict[str, Any], output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    info_cfg = config.get("base", {}).get("info", {})
    gtilde = info_cfg.get("gtilde", 1.0)
    lambda_target = float(info_cfg.get("lambda_target", 1.0))

    lambda_summary = load_json(TE1E_BASE_SUMMARY)
    fluct_summary = load_json(TE1R_FLUCT_SUMMARY)
    fastwin_summary = load_json(TE1O_FASTWIN)
    lambda_phys = float(lambda_summary.get("lambda_phys_mean", lambda_target))
    lambda_norm = float(fastwin_summary.get("two_pi_lambda", 1.0))

    for batch_file in batch_files:
        data = np.load(batch_file, allow_pickle=True)
        delta_g = data["delta_g"]
        delta_I = data["delta_I"]
        delta_psi = data["delta_psi"]
        labels = data["label"]

        samples: List[Dict[str, Any]] = []
        for idx in range(delta_g.shape[0]):
            mapped = map_perturbation(config, delta_g[idx], delta_I[idx], float(delta_psi[idx]))
            geom = compute_geometric_residual(mapped["frw"], gtilde)
            info_resid = compute_informational_residual(mapped["ql"])
            lambda_delta = ((lambda_phys * (1.0 + delta_g[idx].mean())) - lambda_target) / max(lambda_target, 1e-30)
            thermo = compute_entropy_residual(lambda_delta + lambda_norm * 0.0, fluct_summary)
            samples.append(
                {
                    "sample_index": idx,
                    "label": str(labels[idx]),
                    "geom_residual": geom,
                    "informational_residual": info_resid,
                    "thermodynamic_residual": thermo,
                }
            )

        summary = {
            "batch": batch_file.name,
            "config": str(batch_file.resolve()),
            "results": samples,
        }
        out_path = output_dir / f"residuals_{batch_file.stem}.json"
        with out_path.open("w", encoding="utf-8") as handle:
            json.dump(summary, handle, indent=2)
        print(f"Wrote residual summary to {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute RIET residual metrics for perturbation batches")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/riet_residuals.yaml"),
        help="Mapping configuration file",
    )
    parser.add_argument(
        "--batches",
        type=Path,
        default=Path("results"),
        help="Directory containing perturbation_batch_*.npz",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/residual_summaries"),
        help="Output directory for residual JSON files",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    batch_files = sorted(args.batches.glob("perturbation_batch_*.npz"))
    if not batch_files:
        raise SystemExit(f"No perturbation batch files found in {args.batches}")
    evaluate_batches(batch_files, config, args.output)


if __name__ == "__main__":
    main()
