#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Reference: TE_1.R plan (1_1_TE_1R_PLAN.md)
"""
Action-level residual checks for FRW + Psi trajectories.

Computes total energy conservation and Quarter-Lock penalty along solutions
generated by frw_psi_evolve and pt_normal_step_integrator.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

import numpy as np

from frw_psi_solver import frw_psi_evolve, V_eff
from pt_normal_step_integrator import integrate, ql_normal


def friedmann_residual(series: Dict[str, List[float]], gtilde: float) -> float:
    rho_sum = np.array(series["rhoPsi"]) + np.array(series["rho_m"]) + np.array(series["rho_L"])
    lhs = np.array(series["H"]) ** 2
    rhs = (gtilde / 3.0) * rho_sum
    denom = np.maximum(lhs, 1e-12)
    resid = np.abs(lhs - rhs) / denom
    return float(resid.max())


def quarter_lock_penalty(traj: List[List[float]]) -> float:
    n = ql_normal(len(traj[0]))
    penalties = [abs(sum(ni * ki for ni, ki in zip(n, k))) for k in traj]
    return float(max(penalties))


def main() -> None:
    parser = argparse.ArgumentParser(description="Action-level residual checker.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/action_checks"),
        help="Output directory (default: results/action_checks).",
    )
    parser.add_argument("--t-max", type=float, default=2.0, help="FRW integration horizon.")
    parser.add_argument("--dt", type=float, default=1e-3, help="FRW solver timestep.")
    parser.add_argument("--s-max", type=float, default=2.0, help="RG integration horizon (ln μ).")
    parser.add_argument("--ds", type=float, default=1e-3, help="RG integrator step size.")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)

    frw_series = frw_psi_evolve(t_max=args.t_max, dt=args.dt)
    gtilde = 1.0  # default used in solver
    drift = friedmann_residual(frw_series, gtilde)

    k0 = [7 / 512, -0.8090169, -0.78, 0.02, np.pi / 2, 0.125, -1.5, 1.3333333]
    traj, times = integrate(k0, s_max=args.s_max, ds=args.ds, Epsi=0.5)
    ql_penalty = quarter_lock_penalty(traj)

    report = {
        "friedmann_max_residual": drift,
        "ql_max_penalty": ql_penalty,
        "trajectory_length": len(traj),
        "s_max": args.s_max,
        "t_max": args.t_max,
        "dt": args.dt,
        "ds": args.ds,
    }

    (args.output / "action_check.json").write_text(json.dumps(report, indent=2))
    print(
        "[Action] max Friedmann residual "
        f"{report['friedmann_max_residual']:.3e}, max QL penalty {report['ql_max_penalty']:.3e}"
    )


if __name__ == "__main__":
    main()

