#!/usr/bin/env python3
"""
nuclear_be_api.py — UGP Nuclear Binding Energy and Stability Predictor

Two analytical models are available:

  parsimonious  6-term GTE coordinate law (P03 Appendix A).
                0.032 MeV/A 5-fold CV MAE on 1,319 curated NUBASE2020 nuclei.
                Best choice for interpretability and structural analysis.

  extended      9-term law (SPEC_054_ENL Phase 2): same 6 features + proton
                magic-number proximity + neutron magic-number proximity + pairing
                delta.  Trained on 2,548 experimental AME2020 nuclei (full table).
                0.051 MeV/A 5-fold CV MAE across all experimental AME2020 nuclei;
                OOD R²=0.977 on 1,229 AME2020 nuclei absent from original training.
                Best choice for accuracy-sensitive screening across the nuclear chart.

                Note on CV MAE: the extended model's CV MAE (0.051) is higher than
                the parsimonious (0.032) because Phase 2 training includes exotic
                near-drip-line nuclei that are inherently harder to predict.  On the
                original 1,319-nucleus set, the extended model matches or exceeds
                the parsimonious model at every point, and at doubly-magic nuclei
                (e.g. ²⁰⁸Pb) the error is reduced ~10×.

Usage:
    python tools/nuclear_be_api.py --Z 26 --N 30 --task both
    python tools/nuclear_be_api.py --Z 26 --N 30 --task both --model extended
    python tools/nuclear_be_api.py --Z 26 --N 30 --task both --model both
    python tools/nuclear_be_api.py --batch nuclei.json --task both --model extended
    python tools/nuclear_be_api.py --Z 82 --N 126 --task be --output results.json

Input (single nucleus):
    --Z     Proton number (integer, 1–118 supported; up to 190 Category D/exploratory)
    --N     Neutron number (integer)
    --task  be | stability | both (default: both)
    --model parsimonious | extended | both (default: parsimonious)

Input (batch mode):
    --batch  Path to JSON file: list of {"Z": int, "N": int} objects

Output (JSON):
    {
        "Z": 26, "N": 30, "A": 56,
        "model": "extended",
        "binding_energy_per_A_MeV": 8.790,
        "binding_energy_total_MeV": 492.2,
        "stability_score": 0.814,      # raw Ridge score (>0.5 = predicted stable)
        "stability_class": "stable",   # "stable" or "unstable"
        "caveats": {...}
    }

Source: papers/03_nuclear/Nuclear_Physics_From_UGP_Paper.tex, Appendix A (parsimonious)
        papers/03_nuclear/canonical_models/p2_extended_binding_energy_law.txt (extended)
        SPEC_054_ENL_EXTENDED_NUCLEAR_BE_LAW.md
"""

from __future__ import annotations
import argparse
import json
import sys
import math
from typing import Union

# ─── Parsimonious model: 6-term Ridge (P03 Appendix A) ───────────────────────

# Parsimonious model: Phase 2 — trained on 2,548 experimental AME2020 nuclei
# Coefficients from papers/03_nuclear/canonical_models/p2_parsimonious_binding_energy_law.txt
# Generated by: papers/03_nuclear/train_phase2_ame2020.py (2026-05-12)
# Note: CV MAE (0.052) is higher than Phase 1 (0.032) because the Phase 2 set
# includes harder exotic nuclei; interpretable analytical form unchanged.
_P_MEANS  = [3.606561, 3.180870, 3.015068, 0.031690, 0.800648, 0.658774]
_P_SCALES = [0.766471, 0.450747, 0.649385, 0.030825, 0.085491, 0.156698]

_P_BE_INTERCEPT = 8.050975
_P_BE_WEIGHTS   = [0.362256, 1.088939, 0.043017, -0.450372, 1.114560, 0.381767]

_P_STAB_INTERCEPT = 0.388148
_P_STAB_WEIGHTS   = [-1.488826, 3.201347, -1.380612, -0.005484, 0.021654, 0.542883]

# ─── Extended model: 9-term Ridge (SPEC_054_ENL) ──────────────────────────────
# Coefficients from papers/03_nuclear/canonical_models/extended_binding_energy_law.txt
# Generated by: papers/03_nuclear/train_extended_be_law.py (2026-05-12)

# Extended model: Phase 2 — trained on 2,548 experimental AME2020 nuclei
# Coefficients from papers/03_nuclear/canonical_models/p2_extended_binding_energy_law.txt
# Generated by: papers/03_nuclear/train_phase2_ame2020.py (2026-05-12)
_E_MEANS  = [3.606561, 3.180870, 3.015068, 0.031690, 0.800648, 0.658774,
             0.405834, 0.325525, 0.000296]
_E_SCALES = [0.766471, 0.450747, 0.649385, 0.030825, 0.085491, 0.156698,
             0.282725, 0.288419, 0.036563]

_E_BE_INTERCEPT = 8.050975
_E_BE_WEIGHTS   = [0.839866, 0.245905, 0.430530, -0.442599, 1.140340,
                   0.343096, 0.010522, 0.015979, 0.060291]

_E_STAB_INTERCEPT = 0.388148
_E_STAB_WEIGHTS   = [-1.488826, 3.201347, -1.380612, -0.005484, 0.021654,
                      0.542883, -0.012027, -0.066573, -0.035923]

# ─── Magic numbers ────────────────────────────────────────────────────────────
_MAGIC = [2, 8, 20, 28, 50, 82, 126]
_SHELL_SIGMA = 5.0

# ─── Domain bounds ────────────────────────────────────────────────────────────
_Z_MAX_RELIABLE = 118
_A_MAX_RELIABLE = 290


# ─── Feature computation ──────────────────────────────────────────────────────

def _f1_f6(Z: float, N: float) -> list[float]:
    """6 GTE coordinate features (F1–F6)."""
    A = Z + N
    eps = 1e-9
    f1 = math.log(N * (N - 1) / A + 1 + eps)
    f2 = math.log(A ** (2 / 3) + 1)
    f3 = math.log(Z * (Z - 1) / A + 1 + eps)
    f4 = ((N - Z) / A) ** 2
    f5 = math.exp(-Z * (Z - 1) / (100 * A))
    f6 = math.exp(-N * (N - 1) / (100 * A))
    return [f1, f2, f3, f4, f5, f6]


def _f7_f9(Z: int, N: int) -> list[float]:
    """3 extended features: magic-number proximity (Z, N) + pairing."""
    A = Z + N
    f7 = math.exp(-min(abs(Z - m) for m in _MAGIC) / _SHELL_SIGMA)
    f8 = math.exp(-min(abs(N - m) for m in _MAGIC) / _SHELL_SIGMA)
    z_even = (Z % 2 == 0)
    n_even = (N % 2 == 0)
    if z_even and n_even:
        delta = +1.0
    elif (not z_even) and (not n_even):
        delta = -1.0
    else:
        delta = 0.0
    f9 = delta * A ** (-0.75)
    return [f7, f8, f9]


def _standardize(features: list[float], means: list[float],
                  scales: list[float]) -> list[float]:
    return [(x - m) / s for x, m, s in zip(features, means, scales)]


# ─── Prediction functions ─────────────────────────────────────────────────────

def predict_binding_energy(Z: int, N: int, model: str = "parsimonious") -> dict:
    A = Z + N
    feats = _f1_f6(float(Z), float(N))
    if model == "extended":
        feats += _f7_f9(Z, N)
        feats_sc = _standardize(feats, _E_MEANS, _E_SCALES)
        be_per_A = _E_BE_INTERCEPT + sum(w * x for w, x in zip(_E_BE_WEIGHTS, feats_sc))
    else:
        feats_sc = _standardize(feats, _P_MEANS, _P_SCALES)
        be_per_A = _P_BE_INTERCEPT + sum(w * x for w, x in zip(_P_BE_WEIGHTS, feats_sc))

    ood = Z > _Z_MAX_RELIABLE or A > _A_MAX_RELIABLE
    return {
        "binding_energy_per_A_MeV": round(be_per_A, 4),
        "binding_energy_total_MeV": round(be_per_A * A, 3),
        "out_of_domain": ood,
    }


def predict_stability(Z: int, N: int, model: str = "parsimonious") -> dict:
    feats = _f1_f6(float(Z), float(N))
    if model == "extended":
        feats += _f7_f9(Z, N)
        feats_sc = _standardize(feats, _E_MEANS, _E_SCALES)
        score = _E_STAB_INTERCEPT + sum(w * x for w, x in zip(_E_STAB_WEIGHTS, feats_sc))
    else:
        feats_sc = _standardize(feats, _P_MEANS, _P_SCALES)
        score = _P_STAB_INTERCEPT + sum(w * x for w, x in zip(_P_STAB_WEIGHTS, feats_sc))

    stable = score >= 0.5
    ood = Z > _Z_MAX_RELIABLE
    return {
        "stability_score": round(score, 4),
        "stability_class": "stable" if stable else "unstable",
        "out_of_domain": ood,
    }


def _caveats(model: str) -> dict:
    base = {
        "training_domain": "Z ≤ 118, A ≤ ~295 — 2,548 experimental AME2020 nuclei (Phase 2)",
        "ood_warning": "out_of_domain=true means predictions are Category D (exploratory)",
        "source_paper": "papers/03_nuclear/Nuclear_Physics_From_UGP_Paper.tex",
    }
    if model == "parsimonious":
        base.update({
            "model": "Parsimonious 6-term GTE analytical law — Phase 2 (Ridge, 2,548 experimental AME2020 nuclei)",
            "be_accuracy": "0.052 MeV/A 5-fold CV MAE across all experimental AME2020 nuclei "
                           "(0.032 MeV/A on curated 1,319-nucleus Phase 1 set); "
                           "higher CV MAE reflects harder exotic nuclei in full AME2020",
            "stability_accuracy": "Ridge-based stability score; use ML Oracle (98.63% CV) for production classification",
            "recommended_use": "Interpretable structural analysis; zero-dependency closed form",
            "source_coefficients": "papers/03_nuclear/canonical_models/p2_parsimonious_binding_energy_law.txt",
        })
    else:
        base.update({
            "model": "Extended 9-term law — Phase 2 (SPEC_054_ENL): 6 GTE + magic-number proximity + pairing; "
                     "trained on 2,548 experimental AME2020 nuclei",
            "be_accuracy": "0.051 MeV/A 5-fold CV MAE across all experimental AME2020 nuclei; "
                           "OOD R²=0.977 on 1,229 nuclei absent from original training set; "
                           "²⁰⁸Pb error reduced ~10× vs parsimonious",
            "stability_accuracy": "Improved over 6-term across nuclear chart",
            "recommended_use": "Accuracy-sensitive screening across the full measured nuclear chart (Z ≤ 118); "
                               "best for doubly-magic and exotic nuclei",
            "source_coefficients": "papers/03_nuclear/canonical_models/p2_extended_binding_energy_law.txt",
        })
    return base


def predict_nucleus(Z: int, N: int, task: str = "both",
                    model: str = "parsimonious") -> dict:
    """Run prediction(s) for a single nucleus. model: 'parsimonious' | 'extended'."""
    if Z < 1 or N < 1:
        raise ValueError(f"Z and N must be positive integers (got Z={Z}, N={N})")

    A = Z + N
    result: dict = {"Z": Z, "N": N, "A": A, "model": model}

    if task in ("be", "both"):
        result.update(predict_binding_energy(Z, N, model))
    if task in ("stability", "both"):
        stab = predict_stability(Z, N, model)
        result["stability_score"] = stab["stability_score"]
        result["stability_class"] = stab["stability_class"]
        if "out_of_domain" not in result:
            result["out_of_domain"] = stab["out_of_domain"]
        else:
            result["out_of_domain"] = result["out_of_domain"] or stab["out_of_domain"]

    result["caveats"] = _caveats(model)
    return result


def predict_nucleus_both_models(Z: int, N: int, task: str = "both") -> dict:
    """Return predictions from both models for comparison."""
    return {
        "parsimonious": predict_nucleus(Z, N, task, "parsimonious"),
        "extended":     predict_nucleus(Z, N, task, "extended"),
    }


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="UGP Nuclear Binding Energy and Stability API",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--Z", type=int, help="Proton number (single nucleus mode)")
    group.add_argument("--batch", metavar="FILE",
                       help="JSON file with list of {Z, N} dicts (batch mode)")

    parser.add_argument("--N", type=int, help="Neutron number (required with --Z)")
    parser.add_argument(
        "--task",
        choices=["be", "stability", "both"],
        default="both",
        help="Prediction target: be | stability | both (default: both)",
    )
    parser.add_argument(
        "--model",
        choices=["parsimonious", "extended", "both"],
        default="parsimonious",
        help=(
            "Model: parsimonious (6-term, P03 Appendix A) | "
            "extended (9-term, SPEC_054_ENL) | "
            "both — returns side-by-side comparison. (default: parsimonious)"
        ),
    )
    parser.add_argument("--output", metavar="FILE",
                        help="Write JSON output to FILE instead of stdout")

    args = parser.parse_args()

    def _run_single(Z: int, N: int) -> Union[dict, list]:
        if args.model == "both":
            return predict_nucleus_both_models(Z, N, args.task)
        return predict_nucleus(Z, N, args.task, args.model)

    if args.Z is not None:
        if args.N is None:
            parser.error("--N is required when using --Z")
        results = _run_single(args.Z, args.N)
    else:
        with open(args.batch) as fh:
            nuclei = json.load(fh)
        if not isinstance(nuclei, list):
            raise ValueError("Batch file must contain a JSON array of {Z, N} objects")
        results = [_run_single(int(n["Z"]), int(n["N"])) for n in nuclei]

    output = json.dumps(results, indent=2)

    if args.output:
        with open(args.output, "w") as fh:
            fh.write(output + "\n")
        print(f"Results written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
